`ibm-cloud-text-to-speech` integration params
superfaceai/station pull request #103
Opened 2021-11-02 09:12 UTC by janhalama

## Description

This PR adds integration parameters to `ibm-cloud-text-to-speech` provider, it also updates corresponding `speech/synthesis` map.

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-11-02 17:20 UTC, freaz commented
@janhalama when I run locally `yarn capabilities:test capabilities/speech/synthesis/maps/ibm-cloud-text-to-speech.test.ts` tests are not passing.

And same on CI

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/959390/139914303-e91c97ed-7e33-4441-9eb9-726ec5fe1e5b.png">

2021-11-02 17:21 UTC, freaz requested changes
Tests are not passing

2021-11-03 08:13 UTC, janhalama commented
> Tests are not passing

I confirm that when I clone new station and try to run tests they are not passing. When I run tests after recording they pass... I am looking into it.

2021-11-03 10:29 UTC, janhalama commented
Tests are not passing because integration parameters are not configured. In case of `ibm-cloud-text-to-speech` provider integration parameters are used to compose url. Testing lib is not matching recordings when integration parameters are not configured or are configured differently.

2021-11-03 11:12 UTC, freaz commented
Do you plan to fix it?

2021-11-05 12:05 UTC, freaz reviewed
Noticed there are old recordings.json

2021-11-08 08:48 UTC, freaz approved these changes
Looks good

2021-11-08 08:48 UTC, freaz commented on .env.capabilities.example
> +TWILIO_COMMUNICATION_SENDMESSAGE_FROM=+xxx
Should this be here?

2021-11-08 11:27 UTC, janhalama commented on .env.capabilities.example
> +TWILIO_COMMUNICATION_SENDMESSAGE_FROM=+xxx
Removed. Thanks for catch.

2021-11-08 11:31 UTC, merged