feat: Add `chat/send-message` with slack and discord
superfaceai/station pull request #195
Opened 2022-02-04 11:12 UTC by martinalbert

## Description
Adds new profile `chat/send-message` with slack and discord maps.

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I haven't repeated the code. (DRY)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-02-18 10:56 UTC, jnv requested changes

2022-02-18 10:56 UTC, jnv commented on grid/chat/send-message/profile.supr
> +    Identification of destination to retrieve messages from
Copy pasta? :wink: 

```suggestion
    Channel to send the message to
```

2022-02-18 10:56 UTC, jnv commented on grid/chat/send-message/profile.supr
> +    Content of the message
```suggestion
    Contents of the message
```

2022-02-18 10:56 UTC, jnv commented on grid/chat/send-message/maps/send-message.ts
> +  destination: string[],
TBH this API doesn't tell anything about the fact that the second destination is supposed to be non-existent. As a quick workaround, you can define this parameter as a tuple, but consider better function interfaces in the future.

2022-03-03 08:30 UTC, jnv commented
@martinalbert What is the status here? Is this ready?

2022-03-15 15:59 UTC, martinalbert commented
@jnv yes it is ready.

2022-03-22 08:50 UTC, janhalama commented on grid/chat/send-message/maps/discord.suma
> +  set if (details.remainingRequests && details.totalRequests) {
```suggestion
  set if (details.remainingRequests !== undefined && details.totalRequests) {
```

2022-03-22 08:51 UTC, janhalama commented on grid/chat/send-message/maps/slack.suma
> +  set if (details.remainingRequests && details.totalRequests) {
```suggestion
  set if (details.remainingRequests !== undefined && details.totalRequests) {
```

2022-03-22 12:22 UTC, martinalbert commented
@janhalama thanks, I added your suggestions.

2022-03-23 10:23 UTC, janhalama approved these changes
LGTM

2022-03-25 09:37 UTC, jnv approved these changes
:shipit:

2022-03-25 13:40 UTC, merged