feat: Add `chat/threads` profile with discord map
superfaceai/station pull request #201
Opened 2022-02-09 11:00 UTC by martinalbert

## Description

Adds profile `chat/threads` with use-case `GetThreads` and discord map for this use-case.

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I haven't repeated the code. (DRY)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-03-22 08:49 UTC, janhalama commented on grid/chat/threads/maps/discord.suma
> +  set if (details.remainingRequests && details.totalRequests) {
```suggestion
  set if (details.remainingRequests !== undefined && details.totalRequests) {
```

2022-03-23 10:22 UTC, janhalama approved these changes
LGTM

2022-03-25 10:58 UTC, jnv requested changes

2022-03-25 10:58 UTC, jnv commented on grid/chat/threads/profile.supr
> +  result {
This result format doesn't handle pagination.
I know Discord doesn't need it, but it's mentioned in the description. So either add fields for `page` and `nextPage` (which will be always ignored in Discord map), or change the description.

2022-03-25 10:58 UTC, jnv commented on grid/chat/threads/profile.supr
> +  UNIX timestamp in ms (e.g. 1095379198750) when the thread will be archived
```suggestion
  UNIX timestamp in ms (e.g. 1095379198750) when the thread will be archived.
  Some providers limit the lifetime of threads and automatically archive them after some time period of inactivity.
```

2022-03-25 10:58 UTC, jnv commented on grid/chat/threads/profile.supr
> +  Number of members of the retrieved thread
Is this correct?

```suggestion
  Number of users participating in the thread
```

2022-03-25 10:58 UTC, jnv commented on grid/chat/threads/profile.supr
> +model Thread {
If possible, consider adding fields with messages count and the time of the latest message (e.g. `updatedAt` or `lastMessageAt`).

2022-03-25 14:41 UTC, martinalbert commented on grid/chat/threads/profile.supr
> +  Number of members of the retrieved thread
yep

2022-03-25 15:25 UTC, jnv commented on grid/chat/threads/maps/threads.ts
> +  workspaces: string[],
I'd prefer an object with `valid` and `invalid`, but if you insist on using an array, at least type it as a tuple (I think it's like `[valid: string, invalid: string]`

2022-06-09 13:34 UTC, jnv commented
@martinalbert I don't see my comment about pagination being addressed. Do you want to keep it out for now?

2022-06-10 07:10 UTC, jnv requested changes
Missing pagination (or ack)

2022-06-13 09:54 UTC, martinalbert commented
@jnv if you mean [this](https://github.com/superfaceai/station/pull/201#discussion_r835121206) comment, I already removed description about this usecase being paginated in [here](https://github.com/superfaceai/station/pull/201/commits/cbdb5190d3aff1fe50e358d778db70b28a0b29bf).

2022-06-13 10:03 UTC, jnv commented
> if you mean [this](https://github.com/superfaceai/station/pull/201#discussion_r835121206) comment, I already removed description about this usecase being paginated in [here](https://github.com/superfaceai/station/pull/201/commits/cbdb5190d3aff1fe50e358d778db70b28a0b29bf).

OK, my less preferred solution but let's roll with it for now.

2022-06-13 10:05 UTC, jnv approved these changes

2022-06-20 09:26 UTC, merged