feat: add CRUD for Asana tasks
superfaceai/station pull request #289
Opened 2022-11-18 11:12 UTC by martinalbert

## Description
Adds new usecases and maps under profile `project-management/tasks`:
- `ReadAllTasks`,
- `ReadTask`
- `UpdateTask`
- `RemoveTask`

CRM features

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I haven't repeated the code. (DRY)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-11-18 14:11 UTC, jnv commented
@martinalbert Is this ready? I see the tests are failing.

2022-11-18 14:14 UTC, jnv commented
Just from a quick glance:

- I don't see a version bump of the profile, this is (seems?) like a minor change (or are there any breakages?)
- `ReadAllTasks` – I think `ListTasks` is preferred?

2022-11-21 10:01 UTC, janhalama reviewed
I went through it. And I have some suggestions and improvements.

2022-11-21 10:17 UTC, tmladek commented on grid/project-management/tasks/profile.supr
> +usecase ListTasks {
What do you mean? Seems to follow the rest of station, with no missing indents

2022-11-21 10:20 UTC, tmladek commented on grid/project-management/tasks/profile.supr
> +usecase ListTasks {
Oh I see it now 😄 @martinalbert used tabs, which in my VS code config looks just fine; the rest of the file uses spaces

2022-11-21 10:22 UTC, martinalbert commented on grid/project-management/tasks/profile.supr
> +usecase ListTasks {
It's more visible in body of usecases 😄 I also noticed this and vscode won't help for some reason, I'll fix it.

2022-11-21 11:17 UTC, martinalbert commented on grid/project-management/tasks/profile.supr
> +usecase ListTasks {
@janhalama @tmladek should be better now 🙌🏻

2022-11-22 08:15 UTC, janhalama requested changes
I found some issues in the map.

2022-11-22 08:15 UTC, janhalama commented on grid/project-management/tasks/maps/asana.suma
> +        assignee: body.data.assignee.gid,
issue: assignee is nullable

2022-11-22 08:15 UTC, janhalama commented on grid/project-management/tasks/maps/asana.suma
> +      data = {
suggestion(non-blocking): mapping of a task in `CreateTask`, `UpdateTask` and `ReadTask` use cases contains the same code I suggest to refactor the code and move the mapping into operation

2022-11-22 08:15 UTC, janhalama commented on grid/project-management/tasks/maps/asana.suma
> +          // projects: [input.project],
issue: you have commented out code here without any comment, IMO the commented out properties should be updatable

2022-11-22 08:15 UTC, janhalama commented on grid/project-management/tasks/maps/asana.suma
> +        assignee: body.data.assignee.gid,
issue: dtto assignee is nullable

2022-11-22 08:15 UTC, janhalama commented on grid/project-management/tasks/profile.supr
> +usecase ListTasks {
LGTM 🙏

2022-11-22 09:30 UTC, janhalama approved these changes
Looks good 👍

2022-12-06 15:35 UTC, tmladek approved these changes
lgtm, feel free to merge

2022-12-07 12:13 UTC, merged