Feat/align vcs single file content
superfaceai/station pull request #79
Opened 2021-09-28 08:27 UTC by Jakub-Vacek

This PR aligns vcs/single-file-content capability with our conventions
## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I haven't repeated the code. (DRY)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-10-04 07:07 UTC, freaz requested changes
Few minor things, but profile version should be raised in minor except patch.

2021-10-04 07:07 UTC, freaz commented on capabilities/vcs/single-file-content/maps/gitlab.suma
> +     response  {
Nitpick 

```suggestion
     response {
```

2021-10-04 07:07 UTC, freaz commented on capabilities/vcs/single-file-content/maps/gitlab.test.ts
> +            owner: 'Jakub-Vacek',
For github you use astexplorer, does make sense to hire unified?

2021-10-04 07:07 UTC, freaz commented on capabilities/vcs/single-file-content/profile.supr
> +  error {
Adding error to profile should result in minor version update as error handling changes in consumers applications.

2021-10-08 07:42 UTC, zdne approved these changes
🙌🏻

2021-10-12 06:38 UTC, merged